FROM node:22-alpine

RUN apk add --no-cache mysql-client

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY tsconfig.json tsconfig.build.json nest-cli.json ./
COPY src ./src/
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh

RUN npm install && npx prisma generate && npm run build

RUN chown -R node:node /app

EXPOSE 4000

ENTRYPOINT ["sh", "./entrypoint.sh"]
