export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  CLIENTS: '/clients',
  CLIENTS_NEW: '/clients/new',
  CLIENTS_DETAIL: (id: string) => `/clients/${id}`,
  VISA_CASES: '/visa-cases',
  VISA_CASES_NEW: '/visa-cases/new',
  VISA_CASES_DETAIL: (id: string) => `/visa-cases/${id}`,
  VISA_DECISIONS: '/visa-decisions',
  KANBAN: '/kanban',
  APPOINTMENTS: '/appointments',
  NOTIFICATIONS: '/notifications',
  AUDIT_LOGS: '/audit-logs',
  PDF: '/pdf',
  TRACKING: '/tracking',
  USERS: '/users',
  SETTINGS: '/settings',
  BACKUP_CENTER: '/backups',
  SYSTEM_HEALTH: '/system-health',
  SYSTEM_LOGS: '/system-logs',
} as const;
